version: '3'

services:
  postgresql:
    # DockerHUBからimageを取得
    image: postgres:10.10
    # 開放するポートを指定
    ports:
      - "5432:5432"
    # PostgreSQLのユーザ/パスワード/データベースを作成
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      POSTGRES_DB: imgrecognition
      TZ: "Asia/Tokyo"

  django:
    # AWS ECRからimageを取得
    image: {your_account_id}.dkr.ecr.ap-northeast-1.amazonaws.com/django_img_recognition:latest
    # サービス起動後に入力されるコマンドを設定
    command: >
      ash -c "./wait-for-it.sh postgresql:5432 --timeout=100 -- ./migrate.sh &&
      uwsgi --http 0.0.0.0:8001 --module django_img_recognition.wsgi_docker --py-autoreload 1 --logto /dev/stdout"
    # 開放するポートを指定
    ports:
      - "8001:8001"
    # 環境変数を指定
    environment:
      DEBUG: 1
      TZ: "Asia/Tokyo"
    # ローカルのAWS認証情報をコピー
    volumes:
      - $HOME/.aws:/home/app/.aws
    depends_on:
      - postgresql

  nginx:
    # AWS ECRからimageを取得
    image: {your_account_id}.dkr.ecr.ap-northeast-1.amazonaws.com/nginx_dev:latest
    # 開放するポートを指定
    ports:
      - "80:80"
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - django